# criando um arquivo "Gemfile" conseguimos organizar
# as gems que quisermos instalar, utilizando a gem bundle
# p/ instalar: gem install bundler
# dentro da pasta com o arquivo Gemfile
# execute o comando bundler no terminal

source 'http://rubygems.org'

gem 'os'
gem 'date'
gem 'cpf_cnpj'
gem 'win32-sound'
gem 'nokogiri'
gem 'httparty'
